export const ActionTypes = {
    SET_ITEMS: 'SET_ITEMS',
    DELETE_ITEMS: 'DELETE_ITEM',
    UPDATE_ITEM: 'UPDATE_ITEM',
    SELECT_ITEMS: 'SELECT_ITEMS',
    DESELECT_ITEMS: 'DESELECT_ITEMS',
    ISSELECT: 'ISSELECT',
    SET_ITEM: 'SET_ITEM',
    NEW_ITEM: 'NEW_ITEM',
    NEW_ALERT: 'NEW_ALERT',
    UPDATE: 'UPDATE',
    DETAILS: 'DETAILS',
    ERROR: 'ERROR'
}